import MiniTheoryDependencyKernel

open MiniTheoryDependencyKernel

def main : IO Unit := do
  IO.println "══════════════════════════════════════════════════"
  IO.println "  MiniTheoryDependencyKernel v0.1.0"
  IO.println "  Theory Dependency Tracking Kernel"
  IO.println "══════════════════════════════════════════════════"
  IO.println ""
  IO.println "  Core API:"
  IO.println s!"    TheoryNode: name, title, version, path, description, specialized"
  IO.println s!"    DependencyKind: import | bridge | example | test"
  IO.println s!"    DependencyEdge: source, target, kind, description"
  IO.println s!"    TheoryManifest: self, dependencies, dependents"
  IO.println s!"    DependencyGraph: nodes, edges"
  IO.println ""
  IO.println "  Graph Operations:"
  IO.println s!"    empty, addNode, addEdge, findNode, edgesFrom, edgesTo, depsOf"
  IO.println s!"    nodeCount, edgeCount"
  IO.println ""
  IO.println "  Graph Algorithms:"
  IO.println s!"    topologicalOrder, findCycle, transitiveDeps, transitiveDependents"
  IO.println s!"    buildOrder, rebuildOrder, stats"
  IO.println ""
  IO.println "  Properties:"
  IO.println s!"    isAcyclic, isForest, isTree, isDAG, isWeaklyConnected, isValid"
  IO.println s!"    depth, maxDepth, leafTheories, rootTheories, maxWidth"
  IO.println s!"    invariants, connectivity, sourceNodes, sinkNodes, isolatedNodes"
  IO.println ""
  IO.println "  Constructions:"
  IO.println s!"    inducedSubgraph, subgraphOn, downwardClosure, closedSubgraph"
  IO.println s!"    transitiveClosure, condensation, sccs, sccCount"
  IO.println s!"    product, merge, mergeWithBridge, rename, union, intersection"
  IO.println ""
  IO.println "  Morphisms:"
  IO.println s!"    TheoryMorphism, TheoryIsomorphism, GraphIsomorphism"
  IO.println s!"    MutualInterpretability, TheoryEquivalence"
  IO.println ""
  IO.println "  Bridges:"
  IO.println s!"    ToAlgebra, ToTopology, ToGeometry, ToComputation"
  IO.println ""
  IO.println "  Classification:"
  IO.println s!"    DependencyProfile, TheoryClassification"
  IO.println s!"    ConsistencyClass, AxiomatizabilityClass"
  IO.println ""
  IO.println "  Main Theorems:"
  IO.println s!"    main_buildchain_exists: every valid graph has a build order"
  IO.println s!"    condensation_is_acyclic: SCC condensation is always acyclic"
  IO.println s!"    main_buildOrder_deterministic: build order is deterministic"
  IO.println ""
  IO.println "  Standard Examples:"
  IO.println s!"    zfcDependencyGraph, groupTheoryHierarchy, ringTheoryDependency"
  IO.println s!"    algebraicDependencyGraph, topologyDependencyGraph, geometryDependencyGraph"
  IO.println s!"    paDependencyGraph, definitionalExtension, pa_zffin_mutualInterp"
  IO.println ""
  IO.println "  Counterexamples:"
  IO.println s!"    cyclicDependencyGraph, selfDependencyGraph"
  IO.println s!"    mutualDependencyGraph, missingTransitiveDependency"
  IO.println s!"    inconsistentTheoryCombination, nonConservativeExtension"
  IO.println s!"    emptyGraph, disconnectedComponents, diamondDependency"
  IO.println ""
  IO.println "  Run `lake env lean --run Test/Smoke.lean` for tests."
  IO.println "  Run `lake env lean --run Main.lean` to print this menu."
