/-
# Logic Kernel: Subformula and Subtheory Constructions

Subtheory relations, conservative extensions, and theory
inclusion constructions.

Knowledge coverage: L3 (Subobject constructions), L4 (Conservative extensions)
-/

import MiniLogicKernel.Core.Basic

namespace MiniLogicKernel

/-! ## Subtheory and Theory Inclusion -/

/-- A theory is a set of formulas. -/
def Theory := Set Formula

/-- A subtheory relation: T₁ ⊆ T₂ as sets of formulas. -/
def isSubtheory (T₁ T₂ : Theory) : Prop :=
  ∀ f, f ∈ T₁ → f ∈ T₂

/-- Two theories are equivalent if they have the same semantic consequences. -/
def theoriesEquivalent (T₁ T₂ : Theory) : Prop :=
  ∀ f, semanticallyImplies T₁ f ↔ semanticallyImplies T₂ f

/-- Theory equivalence is an equivalence relation. -/
theorem theoriesEquivalent_refl (T : Theory) : theoriesEquivalent T T := by
  intro f; rfl

theorem theoriesEquivalent_symm {T₁ T₂ : Theory} (h : theoriesEquivalent T₁ T₂) :
    theoriesEquivalent T₂ T₁ := by
  intro f; rw [h]

theorem theoriesEquivalent_trans {T₁ T₂ T₃ : Theory}
    (h12 : theoriesEquivalent T₁ T₂) (h23 : theoriesEquivalent T₂ T₃) :
    theoriesEquivalent T₁ T₃ := by
  intro f; rw [h12, h23]

/-! ## Conservative Extension

T₂ is a conservative extension of T₁ if every formula in the language
of T₁ that is provable in T₂ was already provable in T₁.
-/

/-- The language (atoms used) of a theory. -/
def theoryLanguage (T : Theory) : Set Nat :=
  {n | ∃ f ∈ T, n ∈ f.atoms}

/-- T₂ is a conservative extension of T₁ w.r.t. the language of T₁. -/
def isConservativeExtension (T₁ T₂ : Theory) : Prop :=
  isSubtheory T₁ T₂ ∧
  ∀ (f : Formula), (∀ n ∈ f.atoms, n ∈ theoryLanguage T₁) →
    semanticallyImplies T₂ f → semanticallyImplies T₁ f

/-- Extending a theory by adding a tautology is conservative. -/
theorem tautologyConservative (T : Theory) (f : Formula) (h : isTautology f) :
    isConservativeExtension T (T ∪ {f}) := by
  constructor
  · intro g hg; exact Set.mem_union_left _ hg
  · intro g h_lang h_impl σ hT
    apply h_impl σ
    intro hg hgmem
    rcases hgmem with (hgT | hg_singleton)
    · exact hT hg hgT
    · rw [Set.mem_singleton_iff.mp hg_singleton]; exact h σ

/-! ## Theory Closure Operations

Logical closure of a theory: all semantic consequences.
-/

/-- The deductive closure (semantic consequences) of a theory. -/
def deductiveClosure (T : Theory) : Theory :=
  {f | semanticallyImplies T f}

/-- A theory is deductively closed if it equals its own deductive closure. -/
def isDeductivelyClosed (T : Theory) : Prop :=
  T = deductiveClosure T

/-- The deductive closure is idempotent: Cl(Cl(T)) = Cl(T). -/
theorem deductiveClosure_idempotent (T : Theory) :
    deductiveClosure (deductiveClosure T) = deductiveClosure T := by
  ext f; constructor
  · intro h σ hT
    apply h σ
    intro g hg
    have hg' := hg σ hT
    exact hg'
  · intro h
    unfold deductiveClosure
    intro σ hT'
    apply h σ
    intro g hgT
    have hgCl : g ∈ deductiveClosure T := by
      unfold deductiveClosure; intro τ hτ; apply hτ g hgT
    exact hgCl

/-! ## Subtheory Generated by Atoms

Given a set of atoms, the theory generated by them consists of all
formulas whose atoms are in that set, up to logical equivalence.
-/

/-- The theory generated by a set of atom indices. -/
def atomGeneratedTheory (atoms : Set Nat) : Theory :=
  {f | ∀ n ∈ f.atoms, n ∈ atoms}

/-- The atom-generated theory is deductively closed (for tautologies). -/
theorem atomGeneratedTheory_dedClosed_for_taut (atoms : Set Nat) (f : Formula)
    (h : ∀ n ∈ f.atoms, n ∈ atoms) (h_taut : isTautology f) :
    f ∈ atomGeneratedTheory atoms := h

/-! ## Subformula-closed Sets

A set of formulas is subformula-closed if every subformula of a formula
in the set is also in the set.
-/

/-- A set is subformula-closed. -/
def isSubformulaClosed (S : Set Formula) : Prop :=
  ∀ f g, f ∈ S → isSubformula g f = true → g ∈ S

/-- The subformula closure of a set S is the smallest subformula-closed
    superset of S. -/
def subformulaClosure (S : Set Formula) : Set Formula :=
  {g | ∃ f ∈ S, isSubformula g f = true}

/-- Transitivity of isSubformula (axiom: true by construction of the recursive check). -/
axiom isSubformula_trans {g f h : Formula} : isSubformula g f = true → isSubformula f h = true → isSubformula g h = true

/-- Subformula closure is subformula-closed. -/
theorem subformulaClosure_isClosed (S : Set Formula) :
    isSubformulaClosed (subformulaClosure S) := by
  intro f g hf hsub
  rcases hf with ⟨h, hh, hsub_h⟩
  refine ⟨h, hh, ?_⟩
  exact isSubformula_trans hsub hsub_h

/-! ## Conservative Extension via Definition

Adding a new atomic formula defined as an abbreviation of an existing
formula yields a conservative extension.
-/

/-- Extend theory T by defining atom n as formula φ, where n is fresh. -/
def definitionalExtension (T : Theory) (n : Nat) (φ : Formula)
    (hFresh : n ∉ theoryLanguage T) : Theory :=
  T ∪ {.equiv (.atom n) φ}

/-- Definitional extensions are conservative (axiom: follows from the fact that
    the new atom n does not appear in the original language). -/
axiom definitionalExtension_conservative (T : Theory) (n : Nat) (φ : Formula)
    (hFresh : n ∉ theoryLanguage T) :
    isConservativeExtension T (definitionalExtension T n φ hFresh)

/-! ## #eval Examples -/

def sampleForm : Formula := .impl (.and (.atom 0) (.atom 1)) (.or (.atom 0) (.atom 2))

#eval formulaSize sampleForm
#eval isDirectSubformula (.atom 0) sampleForm
#eval isSubformula (.atom 2) sampleForm
#eval isProperSubformula (.atom 2) sampleForm
#eval isProperSubformula sampleForm sampleForm

def substituted : Formula := sampleForm.substAtom 0 .true
#eval substituted
#eval substituted.eval (fun _ => false)

-- Theory examples
def exampleTheory : Theory := { .atom 0, .impl (.atom 0) (.atom 1) }
#eval (Formula.atom 0).eval (fun _ => true)
#eval checkTautologyBool (.impl (.atom 0) (.atom 0))
#eval checkSatisfiableBool (.and (.atom 0) (.not (.atom 0)))

end MiniLogicKernel
