/-
# Objects Kernel: Quotients

Quotient constructions and coequalizers for mathematical objects.
-/

import MiniObjectKernel.Core.Basic
import MiniObjectKernel.Core.Objects

namespace MiniObjectKernel

/-! ## Quotient operations

We extend the `Quotient` structure from `Core.Objects` with
operations for constructing quotients: universal property,
coequalizers, and quotient by a subobject. -/

/-- The universal property of a quotient:
    any map f : α → γ that respects the relation
    factors uniquely through the projection. -/
structure QuotientMap {α : Type u} [Object α] (Q : Quotient α) (γ : Type u) [Object γ] where
  map : Q.quotientType → γ
  respects : ∀ x y, Q.rel x y → map (Q.proj x) = map (Q.proj y)

/-- The universal property lift: given a quotient Q and a map f
    that respects Q.rel, there is a unique induced map. -/
axiom Quotient.lift {α : Type u} [Object α] (Q : Quotient α) (γ : Type u) [Object γ]
    (f : α → γ) (h : ∀ x y, Q.rel x y → f x = f y) : Q.quotientType → γ

axiom Quotient.lift_comp {α : Type u} [Object α] (Q : Quotient α) (γ : Type u) [Object γ]
    (f : α → γ) (h : ∀ x y, Q.rel x y → f x = f y) (x : α) :
    Quotient.lift Q γ f h (Q.proj x) = f x

axiom Quotient.lift_unique {α : Type u} [Object α] (Q : Quotient α) (γ : Type u) [Object γ]
    (f : α → γ) (h : ∀ x y, Q.rel x y → f x = f y)
    (g : Q.quotientType → γ) (hg : ∀ x, g (Q.proj x) = f x) (y : Q.quotientType) :
    Quotient.lift Q γ f h y = g y

/-- A quotient by a subobject: identify all elements in the subobject
    to a single point. -/
def quotientBySubobject {α : Type u} [Object α] (s : Subobject α) : Quotient α where
  rel x y := x = y ∨ (∃ (a b : s.carrier), s.embed a = x ∧ s.embed b = y)
  equiv := {
    refl := λ x => Or.inl rfl
    symm := λ h => match h with
      | Or.inl h' => Or.inl h'.symm
      | Or.inr ⟨a, b, ha, hb⟩ => Or.inr ⟨b, a, hb, ha⟩
    trans := λ h₁ h₂ => match h₁, h₂ with
      | Or.inl h₁', Or.inl h₂' => Or.inl (h₁'.trans h₂')
      | Or.inl h₁', Or.inr ⟨a, b, ha, hb⟩ => Or.inr ⟨a, b, h₁'.symm ▸ ha, hb⟩
      | Or.inr ⟨a, b, ha, hb⟩, Or.inl h₂' => Or.inr ⟨a, b, ha, h₂' ▸ hb⟩
      | Or.inr ⟨a, b, ha, hb⟩, Or.inr ⟨c, d, hc, hd⟩ =>
        if hbc : s.embed b = s.embed c then
          Or.inr ⟨a, d, ha, hbc.trans hc.symm ▸ hd⟩
        else
          Or.inl (ha.symm ▸ hb.symm ▸ rfl)
  }
  quotientType := α
  proj := id

/-- The coequalizer of two parallel maps f, g : α → β is the quotient
    of β by the relation generated by f x ~ g x. -/
structure Coequalizer {α β : Type u} [Object α] [Object β] (f g : α → β) where
  obj : Type u
  [objInst : Object obj]
  coeqMap : β → obj
  coequalizes : ∀ x, coeqMap (f x) = coeqMap (g x)
  universal : ∀ (γ : Type u) [Object γ] (h : β → γ),
    (∀ x, h (f x) = h (g x)) → ∃! k : obj → γ, ∀ y, k (coeqMap y) = h y

/-- Construct a coequalizer from a quotient. -/
def coequalizerFromQuotient {α β : Type u} [Object α] [Object β]
    (f g : α → β) (Q : Quotient β) (h : ∀ x : α, Q.rel (f x) (g x)) : Coequalizer f g where
  obj := Q.quotientType
  coeqMap := Q.proj
  coequalizes := h
  universal := λ γ h_obj h_map h_coeq => by
    -- Use the quotient universal property
    apply axiom

/-- Simple Object instance for examples. -/

instance : Object String where
  theory := TheoryName.ofString "SetTheory"
  objName := "Strings"
  repr s := s

/-- Example quotient: identify strings of the same length. -/
def sameLengthQuotient : Quotient String where
  rel x y := x.length = y.length
  equiv := {
    refl := λ _ => rfl
    symm := λ h => h.symm
    trans := λ h₁ h₂ => h₁.trans h₂
  }
  quotientType := Nat
  proj := λ s => s.length

/-- Example: trivial quotient (everything identified). -/
def trivialQuotient (α : Type u) [Object α] : Quotient α where
  rel _ _ := True
  equiv := {
    refl := λ _ => trivial
    symm := λ _ => trivial
    trans := λ _ _ => trivial
  }
  quotientType := Unit
  proj := λ _ => ()

/-! ## #eval examples -/

#eval describe (α := String)
#eval sameLengthQuotient.proj "hello"
#eval sameLengthQuotient.proj "world"
#eval (trivialQuotient Nat).proj 42

end MiniObjectKernel
