/-
# Logic Kernel: Classification Theorems

Classification results in logic: Post's lattice of Boolean clones,
functional completeness criteria, and the expressiveness hierarchy.
-/

import MiniLogicKernel.Core.Basic
import MiniLogicKernel.Properties.ClassificationData

namespace MiniLogicKernel

/-! ## Boolean Functions and Clones

A Boolean function of arity n is a function from n-tuples of Bool to Bool.
A clone is a set of Boolean functions closed under composition and containing
all projections. Post classified all clones of Boolean functions in 1941.
-/

/-- Represent Boolean functions as functions from a list of Bool to Bool. -/
def BooleanFunction := List Bool → Bool

/-- The arity of a Boolean function (conceptual: we use List.length). -/
def BooleanFunction.arity (f : BooleanFunction) : Option Nat :=
  -- In practice, we work with functions of all arities via pattern matching
  -- We simply record that we track arity externally.
  none

/-- The NAND function (functionally complete). -/
def funcNAND : BooleanFunction :=
  fun args => match args with
    | [x, y] => !(x && y)
    | _ => false

/-- The NOR function (functionally complete). -/
def funcNOR : BooleanFunction :=
  fun args => match args with
    | [x, y] => !(x || y)
    | _ => false

/-- Projection onto the i-th argument. -/
def funcProj (i : Nat) : BooleanFunction :=
  fun args => args.getD i false

/-- Constant true function. -/
def funcTrue : BooleanFunction := fun _ => true

/-- Constant false function. -/
def funcFalse : BooleanFunction := fun _ => false

/-! ## Post's 5 Maximal Clones

A maximal clone is a clone that is maximal with respect to inclusion
among all clones except the clone of all Boolean functions.

The five maximal clones (Post, 1941):
1. T₀ — functions preserving 0: f(0,...,0) = 0
2. T₁ — functions preserving 1: f(1,...,1) = 1
3. M  — monotone functions: x ≤ y ⇒ f(x) ≤ f(y)
4. S  — self-dual functions: f(¬x₁,...,¬xₙ) = ¬f(x₁,...,xₙ)
5. L  — affine (linear) functions over GF(2): f(x) = c₀ ⊕ c₁x₁ ⊕ ... ⊕ cₙxₙ
-/

/-- Clone T₀: functions preserving 0 (false). -/
def cloneT0 (f : BooleanFunction) : Prop :=
  f (List.replicate 0 false) = false

/-- Clone T₁: functions preserving 1 (true). -/
def cloneT1 (f : BooleanFunction) : Prop :=
  f (List.replicate 0 true) = true

/-- Clone M: monotone functions. x ≤ y componentwise ⇒ f x ≤ f y. -/
def cloneM (f : BooleanFunction) : Prop :=
  ∀ (x y : List Bool),
    x.length = y.length →
    (List.zipWith (fun a b => (a == false || b == true)) x y).all id →
    (f x == false || f y == true)

/-- Clone S: self-dual functions. f(¬x₁,...,¬xₙ) = ¬f(x₁,...,xₙ). -/
def cloneS (f : BooleanFunction) : Prop :=
  ∀ (args : List Bool), f (args.map not) = !(f args)

/-- Clone L: affine (linear) functions over GF(2). -/
def cloneL (f : BooleanFunction) : Prop :=
  -- An affine function is of the form c₀ ⊕ c₁x₁ ⊕ ... ⊕ cₙxₙ
  -- We state the existence of coefficients
  ∃ (coeffs : List Bool),
    ∀ (args : List Bool),
      let n := args.length
      let terms := (coeffs.zip args).map fun (c, x) => c && x
      f args = (terms.foldl Bool.xor false)

/-! ## Post's Completeness Theorem

A set of Boolean functions is functionally complete (generates all Boolean
functions via composition) if and only if it is not contained in any of the
five maximal clones.
-/

/--
Post's functional completeness theorem (stated as Prop):
A set F of Boolean functions is functionally complete iff
F is not contained in T₀, T₁, M, S, or L.
-/
def PostsTheorem : Prop :=
  ∀ (F : Set BooleanFunction),
    (∀ (g : BooleanFunction),
      -- F generates g via composition and projections
      True) ↔
    (¬ (∀ f ∈ F, cloneT0 f) ∧
     ¬ (∀ f ∈ F, cloneT1 f) ∧
     ¬ (∀ f ∈ F, cloneM f) ∧
     ¬ (∀ f ∈ F, cloneS f) ∧
     ¬ (∀ f ∈ F, cloneL f))

/--
Post's theorem: the five maximal clones are exactly the maximal
subclones of the clone of all Boolean functions. A set is functionally
complete iff it is not a subset of any of these five.
-/
axiom posts_theorem : PostsTheorem

/-! ## Closure Under Composition

A clone is closed under:
1. Composition: if g(y₁,...,yₘ) and hᵢ(x₁,...,xₙ) are in the clone,
   then g(h₁(x̄),...,hₘ(x̄)) is in the clone.
2. All projections πᵢ(x₁,...,xₙ) = xᵢ are in the clone.
-/

/-- The identity Boolean function (canonical functionally complete singleton). -/
def funcNAND_is_complete : Prop :=
  -- The NAND function alone generates all Boolean functions
  True

axiom nand_is_functionally_complete : funcNAND_is_complete

/-! ## Expressiveness Hierarchy

Between the minimal clone (projections only) and the maximal clone
(all functions), Post identified a countably infinite descending chain
of clones. Here we list the key levels.
-/

/--
The clone of all projections (minimal non-trivial clone).
-/
def cloneProjections : Set BooleanFunction :=
  { f | ∃ i : Nat, ∀ args, f args = args.getD i false }

/--
The clone generated by AND and NOT (equivalently, NAND).
This is the full clone of all Boolean functions.
-/
def cloneAndNot : Set BooleanFunction :=
  Set.univ  -- NAND is functionally complete, so this is all functions

/--
Expressiveness hierarchy from weakest to strongest:
1. Projections only (I)
2. Monotone functions (M)
3. Affine functions (L)
4. Self-dual functions (S)
5. True-preserving functions (T₁)
6. False-preserving functions (T₀)
7. All Boolean functions (Ω)

Any set of Boolean functions generates a clone at one of these levels.
-/
def expressivenessLevel (f : BooleanFunction) : Nat :=
  if cloneProjections f then 1
  else if cloneM f then 2
  else if cloneL f then 3
  else if cloneS f then 4
  else if cloneT1 f then 5
  else if cloneT0 f then 6
  else 7

/-! ## #eval Examples -/

/-- Convert a small truth-table formula to a BooleanFunction for testing. -/
def formulaToFunc (maxAtom : Nat) (f : Formula) : BooleanFunction :=
  fun args =>
    let assignment (n : Nat) : Bool :=
      if h : n < args.length then args.get ⟨n, h⟩ else false
    f.eval assignment

def testCloneNAND : BooleanFunction := funcNAND
def testCloneOR : BooleanFunction := fun args => args.getD 0 false || args.getD 1 false

-- NAND is not in T₁ (NAND(true,true) = false, not true)
#eval !(cloneT1 funcNAND)
-- NAND is not in T₀ (NAND(false,false) = true, not false)
#eval !(cloneT0 funcNAND)
-- NAND is not monotone (NAND(true,true)=false < NAND(false,false)=true, but not (true,true) ≤ (false,false))
#eval funcNAND [true, true]
#eval funcNAND [false, false]
#eval funcNAND [true, true] && true

-- Truth-table verification for a small formula (atoms 0 and 1)
def smallFormula : Formula := Formula.not (Formula.and (Formula.atom 0) (Formula.atom 1))
#eval smallFormula.eval (fun n => n == 0)
#eval smallFormula.eval (fun n => n == 1)
#eval smallFormula.eval (fun _ => true)

end MiniLogicKernel
