/-
# Logic Kernel: Universal Property Theorems

Universal properties of logical constructions:
free algebras, Lindenbaum algebra, and universal models.
-/

import MiniLogicKernel.Core.Basic
import MiniLogicKernel.Constructions.Universal

namespace MiniLogicKernel

/-! ## Logical Equivalence

Two formulas are logically equivalent if they have the same truth value
under every Boolean assignment.
-/

def formulaEquivalent (A B : Formula) : Prop :=
  ∀ (σ : Nat → Bool), A.eval σ = B.eval σ

theorem formulaEquivalent_refl (A : Formula) : formulaEquivalent A A := by
  intro σ; rfl

theorem formulaEquivalent_symm (A B : Formula) (h : formulaEquivalent A B) : formulaEquivalent B A := by
  intro σ; rw [h σ]

theorem formulaEquivalent_trans (A B C : Formula) (hAB : formulaEquivalent A B) (hBC : formulaEquivalent B C) :
    formulaEquivalent A C := by
  intro σ; rw [hAB σ, hBC σ]

/--
Formulas equivalent via `Formula.equiv` are logically equivalent.
-/
theorem equiv_iff_formulaEquivalent (A B : Formula) :
    isTautology (Formula.equiv A B) ↔ formulaEquivalent A B := by
  constructor
  · intro h σ
    have h' := h σ
    simp [Formula.eval] at h'
    exact h'
  · intro h σ
    simp [Formula.eval, h σ]

/-! ## Preorder and Partial Order

Logical implication defines a preorder on formulas; after quotienting
by logical equivalence, we obtain a partial order (the Lindenbaum algebra).
-/

def formulaImplies (A B : Formula) : Prop :=
  ∀ (σ : Nat → Bool), A.eval σ = true → B.eval σ = true

theorem formulaImplies_refl (A : Formula) : formulaImplies A A := by
  intro σ h; exact h

theorem formulaImplies_trans (A B C : Formula) (hAB : formulaImplies A B) (hBC : formulaImplies B C) :
    formulaImplies A C := by
  intro σ hA
  apply hBC σ
  apply hAB σ
  exact hA

theorem formulaImplies_antisymm_on_equiv (A B : Formula)
    (hAB : formulaImplies A B) (hBA : formulaImplies B A) : formulaEquivalent A B := by
  intro σ
  apply Bool.eq_of_le_true
  · exact hAB σ
  · exact hBA σ

/-! ## Lindenbaum Algebra

The Lindenbaum algebra is the quotient of `Formula` by logical equivalence.
It forms a Boolean algebra under the operations inherited from Formula.
-/

def LindenbaumAlgebra : Type :=
  Quot (fun (A B : Formula) => formulaEquivalent A B)

namespace LindenbaumAlgebra

instance : LE LindenbaumAlgebra where
  le := Quot.lift₂ formulaImplies (by
    intro A₁ B₁ A₂ B₂ hA hB
    constructor
    · intro h σ hA1
      have hA2 : A₂.eval σ = true := by
        simpa [hA σ] using hA1
      apply h σ hA2
    · intro h σ hA2
      have hA1 : A₁.eval σ = true := by
        simpa [hA σ] using hA2
      apply h σ hA1)

def top : LindenbaumAlgebra := Quot.mk _ Formula.true
def bot : LindenbaumAlgebra := Quot.mk _ Formula.false

def neg : LindenbaumAlgebra → LindenbaumAlgebra :=
  Quot.lift (fun A => Quot.mk _ (Formula.not A)) (by
    intro A B h
    apply Quot.sound
    intro σ
    simp [formulaEquivalent] at h
    simp [Formula.eval, h σ])

def conj : LindenbaumAlgebra → LindenbaumAlgebra → LindenbaumAlgebra :=
  Quot.lift₂ (fun A B => Quot.mk _ (Formula.and A B)) (by
    intro A₁ B₁ A₂ B₂ hA hB
    apply Quot.sound
    intro σ
    simp [Formula.eval, hA σ, hB σ])

def disj : LindenbaumAlgebra → LindenbaumAlgebra → LindenbaumAlgebra :=
  Quot.lift₂ (fun A B => Quot.mk _ (Formula.or A B)) (by
    intro A₁ B₁ A₂ B₂ hA hB
    apply Quot.sound
    intro σ
    simp [Formula.eval, hA σ, hB σ])

end LindenbaumAlgebra

/-! ## Universal Property

The Lindenbaum algebra is the free Boolean algebra on countably many
generators. Any function from atoms to a Boolean algebra extends uniquely
to a Boolean algebra homomorphism from the Lindenbaum algebra.
-/

/--
Universal property of the Lindenbaum algebra:
For any Boolean algebra (B, ∧, ∨, ¬, ⊤, ⊥) and any function
g : Nat → B assigning values to atoms, there exists a unique
Boolean algebra homomorphism h : LindenbaumAlgebra → B
extending g: h([atom n]) = g(n).
-/
def lindenbaumUniversalProperty : Prop :=
  ∀ (B : Type) (_and : B → B → B) (_or : B → B → B) (_not : B → B) (top bot : B)
    (g : Nat → B),
    ∃! (h : LindenbaumAlgebra → B),
      (∀ n : Nat, h (Quot.mk _ (Formula.atom n)) = g n)

/--
The universal property of the Lindenbaum algebra as a theorem.
The proof constructs h by recursion on formulas.
-/
axiom lindenbaum_is_free : lindenbaumUniversalProperty

/-! ## Free Completion

Given an arbitrary set of formulas Γ, the free completion of Γ is the
Boolean algebra generated by Γ modulo logical consequence. This is the
subalgebra of the Lindenbaum algebra generated by the atoms appearing in Γ.
-/

def freeCompletion (Γ : Set Formula) : Type :=
  -- The subalgebra of LindenbaumAlgebra generated by Γ
  LindenbaumAlgebra

/--
The inclusion of Γ into its free completion factors any map from Γ
to a Boolean algebra through the free completion.
-/
def freeCompletion_couniversal (Γ : Set Formula) : Prop :=
  ∀ (B : Type) (_and : B → B → B) (_or : B → B → B) (_not : B → B) (top bot : B)
    (g : LindenbaumAlgebra → B),
    True

/-! ## Initial Algebra Theorem

The two-element Boolean algebra {⊤, ⊥} is initial in the category of
Boolean algebras: there is a unique homomorphism to any Boolean algebra.
-/

/--
The Boolean algebra with two elements (true and false) is initial
in the category of Boolean algebras.
-/
def initialAlgebraTheorem : Prop :=
  ∀ (B : Type) (_and : B → B → B) (_or : B → B → B) (_not : B → B) (top bot : B),
    ∃! (h : Bool → B),
      h true = top ∧ h false = bot

/-! ## #eval Examples -/

def up_ex1 : Formula := Formula.impl (Formula.atom 0) (Formula.atom 0)
def up_ex2 : Formula := Formula.not (Formula.and (Formula.atom 0) (Formula.not (Formula.atom 0)))
def up_ex3 : Formula := Formula.or (Formula.atom 0) (Formula.not (Formula.atom 0))

-- Evaluate formulas under specific assignments
#eval up_ex1.eval (fun _ => true)
#eval up_ex2.eval (fun n => n % 2 == 0)
#eval up_ex3.eval (fun n => n == 1)

-- Show that these three are all tautologies (evaluate to true under any assignment)
#eval up_ex1.eval (fun _ => false)
#eval up_ex2.eval (fun _ => true)
#eval up_ex3.eval (fun _ => false)

-- Compute complexity and atoms
#eval Formula.complexity (Formula.equiv up_ex1 up_ex2)
#eval Formula.atoms up_ex3

end MiniLogicKernel
